{% set name = "azure-datalake-store" %}
{% set version = "0.0.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b871ebb3bcfd292e8a062dbbaacbc132793d98f1b60f549a8c3b672619603fc1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cffi
    - adal >=0.4.2
    - requests >=2.20.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure.datalake.store

about:
  home: http://github.com/Azure/azure-data-lake-store-python
  license: MIT
  license_family: MIT
  license_file: License.txt
  summary: This project is the Python filesystem library for Azure Data Lake Store

  description: |
    A pure-python interface to the Azure Data-lake Storage system,
    providing pythonic file-system and file objects, seamless transition
    between Windows and POSIX remote paths, high-performance up- and down-loader.
  doc_url: http://github.com/Azure/azure-data-lake-store-python
  dev_url: http://github.com/Azure/azure-data-lake-store-python

extra:
  recipe-maintainers:
    - dillonroach
    - scopatz
    - costrouc
    - dhirschfeld
